services:
  chromadb:
    image: chromadb/chroma:latest
    container_name: chromadb
    ports:
      - "8000:8000"
    environment:
      - CHROMA_SERVER_HOST=0.0.0.0
      - CHROMA_SERVER_HTTP_PORT=8000
      - PERSIST_DIRECTORY=/chroma/data
    volumes:
      - chromadb_data:/chroma/data
    networks:
      - vector-db-network
    restart: unless-stopped
    labels:
      - "project=vector-db"
      - "component=database"
      - "db_type=chromadb"

  # Qdrant vector database
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - vector-db-network
    restart: unless-stopped
    labels:
      - "project=vector-db"
      - "component=database"
      - "db_type=qdrant"

  # Weaviate vector database
  weaviate:
    image: semitechnologies/weaviate:latest
    container_name: weaviate
    ports:
      - "8081:8080"
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
    volumes:
      - weaviate_data:/var/lib/weaviate
    networks:
      - vector-db-network
    restart: unless-stopped
    labels:
      - "project=vector-db"
      - "component=database"
      - "db_type=weaviate"

volumes:
  chromadb_data:
  qdrant_data:
  weaviate_data:

networks:
  vector-db-network:
    driver: bridge